=== A-rgonaut/LM-32_AtChannel_Full-Stack_Social_Microblogging_Platform/Progetto WSDA/xml/note.dtd
<!ELEMENT root (note+)>
        <!ELEMENT note (date,to,from,object,message)>
        <!ATTLIST note day CDATA #REQUIRED month CDATA #REQUIRED>
        <!ATTLIST note year CDATA #IMPLIED>
            <!ELEMENT date EMPTY>
            <!ATTLIST date timestamp CDATA #REQUIRED>
            <!ELEMENT to (#PCDATA)>
            <!ELEMENT from (#PCDATA)>
            <!ELEMENT object (#PCDATA)>
            <!ELEMENT message (#PCDATA)>

=== A-rgonaut/LM-32_AtChannel_Full-Stack_Social_Microblogging_Platform/Progetto WSDA/xml/note.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE root SYSTEM "note.dtd">

<root>
    <note day="" month="">
        <date timestamp=""/>
        <to></to>
        <from></from>
        <object></object>
        <message></message>
    </note>
    
    <note day="" month="">
        <date timestamp=""/>
        <to></to>
        <from></from>
        <object></object>
        <message></message>
    </note>
</root>
