=== A-rgonaut/LM-32_AtChannel_Full-Stack_Social_Microblogging_Platform/atChannel/src/main/resources/static/xml/post.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="posts">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="post" type="postType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="postType">
        <xs:sequence>
            <xs:element name="header" type="headerType"/>
            <xs:element name="main" type="mainType"/>
            <xs:element name="footer" type="footerType"/>
        </xs:sequence>

        <xs:attribute name="id" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:int"/>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="headerType">
        <xs:sequence>
            <xs:element name="date" type="xs:date"/>
            <xs:element name="username">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[a-zA-Z0-9 ]{4,}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="nametag">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="@[a-z]{4,}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="pic" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="mainType">
        <xs:sequence>
            <xs:element name="body">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="280"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="attach" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="footerType">
        <xs:sequence>
            <xs:element name="likes">
                <xs:complexType>
                    <xs:attribute name="nLikes" type="xs:nonNegativeInteger" default="0"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="comments">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="comment" type="postType" minOccurs="0" maxOccurs="5"/>
                    </xs:sequence>
                    <xs:attribute name="nComments" type="xs:nonNegativeInteger" default="0"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== A-rgonaut/LM-32_AtChannel_Full-Stack_Social_Microblogging_Platform/Progetto WSDA/xml/post.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<posts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="post.xsd">

    <post id="100">
        <header>
            <date>2020-01-01</date>
            <username>Mario Rossi</username>
            <nametag>@mariorossi</nametag>
            <pic>assets/img/user_icon.png</pic>
        </header>
        <main>
            <body>Lorem ipsum odor amet, consectetuer adipiscing elit. Ante sodales ornare integer leo per. Non vestibulum nec aenean primis suspendisse nascetur. Per pharetra natoque ipsum orci sem. Habitasse malesuada imperdiet; semper per augue dolor sollicitudin ipsum varius.</body>
        </main>
        <footer>
            <likes nLikes="10"/>
            <comments nComments="2">
                <comment id="110">
                    <header>
                        <date>2020-01-01</date>
                        <username>Luigi Verdi</username>
                        <nametag>@luigiverdi</nametag>
                        <pic>assets/img/user_icon.png</pic>
                    </header>
                    <main>
                        <body>Well done</body>
                    </main>
                    <footer>
                        <likes nLikes="2"/>
                        <comments nComments="1"/>
                    </footer>
                </comment>

                <comment id="120">
                    <header>
                        <date>2020-01-01</date>
                        <username>Marco Bianchi</username>
                        <nametag>@marcobianchi</nametag>
                        <pic>assets/img/user_icon.png</pic>
                    </header>
                    <main>
                        <body>Javascript is fun!</body>
                    </main>
                    <footer>
                        <likes nLikes="0"/>
                        <comments nComments="0"/>
                    </footer>
                </comment>
            </comments>
        </footer>
    </post>

    <post id="200">
        <header>
            <date>2020-02-02</date>
            <username>Luigi Verdi</username>
            <nametag>@luigiverdi</nametag>
            <pic>assets/img/user_icon.png</pic>
        </header>
        <main>
            <body>I pleased to announce this post have an image with XML!</body>
            <attach>assets/img/a.png</attach>
        </main>
        <footer>
            <likes nLikes="15"/>
            <comments nComments="1">
                <comment id="210">
                    <header>
                        <date>2020-02-02</date>
                        <username>Mario Rossi</username>
                        <nametag>@mariorossi</nametag>
                        <pic>assets/img/user_icon.png</pic>
                    </header>
                    <main>
                        <body>Nice bro I'm proud of you</body>
                    </main>
                    <footer>
                        <likes nLikes="5"/>
                        <comments nComments="2"/>
                    </footer>
                </comment>
            </comments>
        </footer>
    </post>

    <post id="300">
        <header>
            <date>2020-03-03</date>
            <username>Marco Bianchi</username>
            <nametag>@marcobianchi</nametag>
            <pic>assets/img/user_icon.png</pic>
        </header>
        <main>
            <body>This post is only to alternate only text post and post with image. Lorem ipsum odor amet, consectetuer adipiscing elit. Ante sodales ornare integer leo per. Non vestibulum nec aenean primis suspendisse nascetur. Per pharetra natoque ipsum orci sem.</body>
        </main>
        <footer>
            <likes nLikes="3"/>
            <comments nComments="2">
                <comment id="310">
                    <header>
                        <date>2020-03-03</date>
                        <username>Mario Rossi</username>
                        <nametag>@mariorossi</nametag>
                        <pic>assets/img/user_icon.png</pic>
                    </header>
                    <main>
                        <body>So boooring...</body>
                    </main>
                    <footer>
                        <likes nLikes="4"/>
                        <comments nComments="2"/>
                    </footer>
                </comment>

                <comment id="320">
                    <header>
                        <date>2020-03-03</date>
                        <username>Luigi Verdi</username>
                        <nametag>@luigiverdi</nametag>
                        <pic>assets/img/user_icon.png</pic>
                    </header>
                    <main>
                        <body>Please Bro we want more content!</body>
                    </main>
                    <footer>
                        <likes nLikes="10"/>
                        <comments nComments="4"/>
                    </footer>
                </comment>
            </comments>
        </footer>
    </post>

    <post id="400">
        <header>
            <date>2020-04-04</date>
            <username>Argonaut</username>
            <nametag>@argonaut</nametag>
            <pic>assets/img/user_icon.png</pic>
        </header>
        <main>
            <body>Hi everybody I'm new, check it out my first post with image</body>
            <attach>assets/img/b.png</attach>
        </main>
        <footer>
            <likes nLikes="24"/>
            <comments nComments="1">
                <comment id="410">
                    <header>
                        <date>2020-04-04</date>
                        <username>Mario Rossi</username>
                        <nametag>@mariorossi</nametag>
                        <pic>assets/img/user_icon.png</pic>
                    </header>
                    <main>
                        <body>Nice job newest! Take a look also to my new image</body>
                        <attach>assets/img/c.png</attach>
                    </main>
                    <footer>
                        <likes nLikes="17"/>
                        <comments nComments="6"/>
                    </footer>
                </comment>
            </comments>
        </footer>
    </post>
</posts>

=== A-rgonaut/LM-32_AtChannel_Full-Stack_Social_Microblogging_Platform/atChannel/src/main/resources/static/xml/post2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<posts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="post.xsd">

    <post id="500">
        <header>
            <date>2020-05-05</date>
            <username>Argonaut</username>
            <nametag>@argonaut</nametag>
            <pic>assets/img/user_icon.png</pic>
        </header>
        <main>
            <body>This post come from the second file XML</body>
        </main>
        <footer>
            <likes nLikes="34"/>
            <comments nComments="3">
                <comment id="510">
                    <header>
                        <date>2020-05-05</date>
                        <username>Mario Rossi</username>
                        <nametag>@mariorossi</nametag>
                        <pic>assets/img/user_icon.png</pic>
                    </header>
                    <main>
                        <body>This comment too</body>
                    </main>
                    <footer>
                        <likes nLikes="3"/>
                        <comments nComments="2"/>
                    </footer>
                </comment>

                <comment id="520">
                    <header>
                        <date>2020-05-05</date>
                        <username>Luigi Verdi</username>
                        <nametag>@luigiverdi</nametag>
                        <pic>assets/img/user_icon.png</pic>
                    </header>
                    <main>
                        <body>Also me!</body>
                    </main>
                    <footer>
                        <likes nLikes="2"/>
                        <comments nComments="1"/>
                    </footer>
                </comment>

                <comment id="530">
                    <header>
                        <date>2020-05-05</date>
                        <username>Marco Bianchi</username>
                        <nametag>@marcobianchi</nametag>
                        <pic>assets/img/user_icon.png</pic>
                    </header>
                    <main>
                        <body>me too!</body>
                    </main>
                    <footer>
                        <likes nLikes="2"/>
                        <comments nComments="0"/>
                    </footer>
                </comment>
            </comments>
        </footer>
    </post>

    <post id="600">
        <header>
            <date>2020-06-06</date>
            <username>Mario Rossi</username>
            <nametag>@mariorossi</nametag>
            <pic>assets/img/user_icon.png</pic>
        </header>
        <main>
            <body>Very interesting coming from another XML, but check this image</body>
            <attach>assets/img/b.png</attach>
        </main>
        <footer>
            <likes nLikes="11"/>
            <comments nComments="2">
                <comment id="610">
                    <header>
                        <date>2020-06-06</date>
                        <username>Luigi Verdi</username>
                        <nametag>@luigiverdi</nametag>
                        <pic>assets/img/user_icon.png</pic>
                    </header>
                    <main>
                        <body>Nice Bro but this is better</body>
                        <attach>assets/img/a.png</attach>
                    </main>
                    <footer>
                        <likes nLikes="2"/>
                        <comments nComments="1"/>
                    </footer>
                </comment>

                <comment id="620">
                    <header>
                        <date>2020-01-01</date>
                        <username>Marco Bianchi</username>
                        <nametag>@marcobianchi</nametag>
                        <pic>assets/img/user_icon.png</pic>
                    </header>
                    <main>
                        <body>C'mon guys, don't argue</body>
                    </main>
                    <footer>
                        <likes nLikes="0"/>
                        <comments nComments="0"/>
                    </footer>
                </comment>
            </comments>
        </footer>
    </post>

    <post id="700">
        <header>
            <date>2020-07-07</date>
            <username>Marco Bianchi</username>
            <nametag>@marcobianchi</nametag>
            <pic>assets/img/user_icon.png</pic>
        </header>
        <main>
            <body>Last one text only post, because I'm tired to write random text</body>
        </main>
        <footer>
            <likes nLikes="11"/>
            <comments nComments="1">
                <comment id="710">
                    <header>
                        <date>2020-07-07</date>
                        <username>Argonaut</username>
                        <nametag>@argonaut</nametag>
                        <pic>assets/img/user_icon.png</pic>
                    </header>
                    <main>
                        <body>I see bro, so I put one last comment with image</body>
                        <attach>assets/img/c.png</attach>
                    </main>
                    <footer>
                        <likes nLikes="2"/>
                        <comments nComments="1"/>
                    </footer>
                </comment>
            </comments>
        </footer>
    </post>
</posts>
